### ISSUE TITLE
incorrect cmc parse

### ISSUE THREAD

**Issue by SashaSenichkin** [SashaSenichkin/MtgParser#29]
Великан Бобового Ростка / Шаги Плодородия
Златовласая Незваная Гостья / Идем Домой
Скульптор Течения / Огнеметная Соната
Пикси-Гипнотизер / Дурманящий Взор

Правильно использовать Верхнее значение В вызове первое
можно проверить по подтипу Adventure

**Comment by SashaSenichkin** [comment]
note! get right answers

**Comment by enterfreed** [comment]
Великан Бобового Ростка / Шаги Плодородия cmc: 7
Златовласая Незваная Гостья / Идем Домой  cmc: 1
Скульптор Течения / Огнеметная Соната: здесь сложнее, это две равноправные карты в одной, не помню как мы решили такие СМС вносить, если не решили - обсудим.
Пикси-Гипнотизер / Дурманящий Взор cmc: 2
