### ISSUE TITLE
Price modification

### ISSUE THREAD

**Issue by enterfreed** [SashaSenichkin/MtgParser#8]
Цена: 0.950000000000000000000000000000 $. (CardSetId 240 Flood of Tears-карта  Сет M20)
Я в принципе на стороне php могу обрезать лишнее, но думаю в базе 2 знаков после запятой будет достаточно для долларов на этапе парсинга цены.

**Comment by SashaSenichkin** [comment]
слу, походу, это разница в CLR типе при переходе от базы к пхп.. тебе придётся резать у себя..

**Comment by enterfreed** [comment]
Ок
