### ISSUE TITLE
rarities 

### ISSUE THREAD

**Issue by enterfreed** [SashaSenichkin/MtgParser#9]
Выставь у себя плиз значения с большой буквы, чтобы каждый раз не править
![image](https://user-images.githubusercontent.com/98914249/188223004-4fdbe807-05bb-462e-bbf0-02181bf0f631.png)
![image](https://user-images.githubusercontent.com/98914249/188223132-007d745d-79c9-4bcb-8fa5-1429dd887e7a.png)

common-> Common
обычная-> Обычная и т.д.

**Comment by SashaSenichkin** [comment]
поменял. можешь поправить ручками, со следующим обновлением уже автоматом будет

**Comment by enterfreed** [comment]
принято
